# Generated by Django 4.1.3 on 2022-11-18 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Company_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=300)),
                ('email', models.EmailField(max_length=200)),
                ('phone_no', models.CharField(max_length=12)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyAdmin.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='con_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companyAdmin.county'),
        ),
        migrations.AddField(
            model_name='city',
            name='st_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companyAdmin.state'),
        ),
    ]
