# Generated by Django 4.1.3 on 2022-11-18 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyAdmin', '0002_alter_company_detail_city_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_detail',
            name='city_id',
        ),
        migrations.AddField(
            model_name='company_detail',
            name='city',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='companyAdmin.city'),
            preserve_default=False,
        ),
    ]
