# Generated by Django 4.1.3 on 2022-11-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyAdmin', '0003_remove_company_detail_city_id_company_detail_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='con_id',
        ),
        migrations.RemoveField(
            model_name='city',
            name='st_id',
        ),
    ]
