# Generated by Django 4.1.3 on 2022-11-18 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyAdmin', '0004_remove_city_con_id_remove_city_st_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_detail',
            name='country',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='companyAdmin.county'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company_detail',
            name='state',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='companyAdmin.state'),
            preserve_default=False,
        ),
    ]
