# Generated by Django 4.1.3 on 2022-11-18 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyAdmin', '0005_company_detail_country_company_detail_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='County',
            new_name='Country',
        ),
    ]
