# Generated by Django 4.1.3 on 2022-11-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyAdmin', '0006_rename_county_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=150)),
                ('birthday', models.DateField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('intrested', models.CharField(max_length=150)),
                ('lead_sources', models.CharField(max_length=150)),
                ('remarks', models.TextField(max_length=500)),
                ('assigned', models.CharField(max_length=150)),
                ('status', models.BooleanField(max_length=150)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
