# Generated by Django 4.1.3 on 2022-11-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyAdmin', '0007_leadcreate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcreate',
            name='status',
            field=models.CharField(max_length=150),
        ),
    ]
