# Generated by Django 4.1.3 on 2022-11-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyAdmin', '0009_alter_leadcreate_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcreate',
            name='date_create',
            field=models.DateField(),
        ),
    ]
