# Generated by Django 4.1.3 on 2022-11-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyAdmin', '0010_alter_leadcreate_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcreate',
            name='contact',
            field=models.CharField(default='1', max_length=12),
            preserve_default=False,
        ),
    ]
