# Generated by Django 4.1.3 on 2022-11-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyAdmin', '0011_leadcreate_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcreate',
            name='address',
            field=models.CharField(default='1', max_length=300),
            preserve_default=False,
        ),
    ]
