# Generated by Django 4.1.3 on 2022-11-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyAdmin', '0013_calllogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllogs',
            name='end_datetime',
            field=models.DateTimeField(auto_now_add=True, default='2022-11-17 14:28:27'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calllogs',
            name='start_datetime',
            field=models.CharField(default='2022-11-17', max_length=50),
            preserve_default=False,
        ),
    ]
