# Generated by Django 4.1.3 on 2022-11-22 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyAdmin', '0014_calllogs_end_datetime_calllogs_start_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calllogs',
            old_name='log_typ',
            new_name='logs',
        ),
    ]
