# Generated by Django 4.1.3 on 2022-11-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyAdmin', '0015_rename_log_typ_calllogs_logs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calllogs',
            old_name='logs',
            new_name='name',
        ),
    ]
