# Generated by Django 4.1.3 on 2022-11-22 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyAdmin', '0017_calllogs_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllogs',
            name='lead_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='companyAdmin.leadcreate'),
            preserve_default=False,
        ),
    ]
