# Generated by Django 4.1.3 on 2022-11-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyAdmin', '0019_leadcreate_alternat_no_leadcreate_permanent_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calllogs',
            old_name='name',
            new_name='calllogs',
        ),
    ]
