# Generated by Django 4.1.3 on 2022-11-23 10:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companyAdmin', '0020_rename_name_calllogs_calllogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CallLogs',
            new_name='Call_Details',
        ),
        migrations.RenameField(
            model_name='call_details',
            old_name='calllogs',
            new_name='cls',
        ),
        migrations.RenameField(
            model_name='call_details',
            old_name='end_datetime',
            new_name='end_dt',
        ),
        migrations.RenameField(
            model_name='call_details',
            old_name='lead_id',
            new_name='led_id',
        ),
        migrations.RenameField(
            model_name='call_details',
            old_name='remark',
            new_name='rem',
        ),
        migrations.RenameField(
            model_name='call_details',
            old_name='start_datetime',
            new_name='str_dt',
        ),
    ]
