# Generated by Django 4.1.3 on 2022-11-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyAdmin', '0021_rename_calllogs_call_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call_details',
            name='created_by',
            field=models.CharField(max_length=50),
        ),
    ]
