# Generated by Django 4.1.3 on 2022-11-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyAdmin', '0023_alter_call_details_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcreate',
            name='date_create',
            field=models.DateTimeField(),
        ),
    ]
