# Generated by Django 4.1.3 on 2022-11-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyAdmin', '0024_alter_leadcreate_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcreate',
            name='date_create',
            field=models.TimeField(),
        ),
    ]
