# Generated by Django 4.1.3 on 2022-11-28 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companyAdmin', '0025_alter_leadcreate_date_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('led_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyAdmin.leadcreate')),
            ],
        ),
    ]
