# Generated by Django 4.1.3 on 2022-12-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyAdmin', '0026_notes_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcreate',
            name='date_create',
            field=models.DateField(),
        ),
    ]
